# Generated by Django 4.2.5 on 2023-09-19 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vs_account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
