# Generated by Django 3.2 on 2023-09-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vote', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voted_polls',
            field=models.ManyToManyField(blank=True, to='vote.Poll'),
        ),
    ]
