# Generated by Django 4.2.5 on 2023-09-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_initial'),
        ('accounts', '0002_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_polls',
            field=models.ManyToManyField(blank=True, to='vote.poll'),
        ),
    ]
